trigger:
 branches:
   include:
     - main
variables:
  BACKEND_RESOURCE_GROUP: 'rg-tfstate-devops-eus-01'
  BACKEND_STORAGE_ACCOUNT: 'satfstateeus01'
  BACKEND_CONTAINER: 'tfstate'
  BACKEND_KEY_DEV: 'dev.terraform.tfstate'
  AZURE_SERVICE_CONNECTION: 'microtodoui-dev-eus'
  workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

stages:
  - stage: erraform_Dev
    displayName: "Terraform Dev Deployment"
    jobs:
      - job: Dev
        pool:
         name: microtodoui
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            backendServiceArm: '$(AZURE_SERVICE_CONNECTION)'
            backendAzureRmStorageAccountName: '$(BACKEND_STORAGE_ACCOUNT)'
            backendAzureRmContainerName: '$(BACKEND_CONTAINER)'
            backendAzureRmKey: '$(BACKEND_KEY_DEV)'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(workingDirectory)'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(workingDirectory)'
            environmentServiceNameAzureRM: '$(AZURE_SERVICE_CONNECTION)'
  - stage: ManualIntervention
    jobs:
      - job: ManualIntervention
        displayName: 'Manual Intervention'
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'bipinsngh16@gmail.com'
            approvers: 'bipinsngh16@gmail.com'
            instructions: 'Pls approve'
  - stage: Apply
    dependsOn: ManualIntervention
    jobs:
      - job: Apply
        pool:
         name: microtodoui
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            backendServiceArm: '$(AZURE_SERVICE_CONNECTION)'
            backendAzureRmStorageAccountName: '$(BACKEND_STORAGE_ACCOUNT)'
            backendAzureRmContainerName: '$(BACKEND_CONTAINER)'
            backendAzureRmKey: '$(BACKEND_KEY_DEV)'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            backendServiceArm: '$(AZURE_SERVICE_CONNECTION)'
            backendAzureRmStorageAccountName: '$(BACKEND_STORAGE_ACCOUNT)'
            backendAzureRmContainerName: '$(BACKEND_CONTAINER)'
            backendAzureRmKey: '$(BACKEND_KEY_DEV)'